# -*- coding: utf-8 -*-
"""
/***************************************************************************
 CompareClassA
                                 A QGIS plugin
 Compare two datasets of GPKG pointZ geometry based on french legislation formatting "class A".
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-08-13
        copyright            : (C) 2024 by Vincent Bénet
        email                : vincent.benet@outlook.fr
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load CompareClassA class from file CompareClassA.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .compare_class_a import CompareClassA
    return CompareClassA(iface)
